nota1=input("Digite a primeira nota: ")
nota2=input("Digite a segunda nota: ")
nota3=input("Digite a terceira nota: ")
nota4=input("Digite a quarta nota: ")
print("A média aritmética é",(float(nota1)+float(nota2)+float(nota3)+float(nota4))/4)
